[package]
name = "eksperimenter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.57"